global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: '/prometheus/'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:8081']